# Generated by Django 4.0.1 on 2022-01-18 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='statud',
            new_name='status',
        ),
    ]
